#!/usr/bin/env bash
# Script to config domain zone to point to load balancer

# Function to display subdomain information
display_subdomain_info() {
    local domain=$1
    local subdomain=$2

    # If subdomain is not provided, use default subdomains
    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    # Loop through subdomains and display information
    for sub in "${subdomains[@]}"; do
        # Retrieve DNS information using dig command
        dns_info=$(dig $sub.$domain | awk '/ANSWER SECTION:/ { getline; print $4, $5 }')

        # Display subdomain information
        echo "The subdomain $sub is a $dns_info and points to $(dig $sub.$domain +short)"
    done
}

# Check if domain and subdomain arguments are provided
if [ $# -eq 1 ]; then
    display_subdomain_info "$1"
elif [ $# -eq 2 ]; then
    display_subdomain_info "$1" "$2"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi
